version: '3'
services:
  drupal:
    volumes:
      - drupal:/var/www/html
    image: drupal:8-apache
    ports:
      - 8000:80
    networks:
      - net

  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: drupal
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - net
volumes:
  drupal:
networks:
  net:

  #@l*%g(URm@jL73vd2Z